// This file is automatically generated. Do not edit it directly.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instanciate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "12.2.3 (519615d)"
  }
  public: {
    Tables: {
      categories: {
        Row: {
          created_at: string | null
          description: string | null
          id: string
          image_url: string | null
          is_active: boolean | null
          name: string
          parent_id: string | null
          slug: string
          sort_order: number | null
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          description?: string | null
          id?: string
          image_url?: string | null
          is_active?: boolean | null
          name: string
          parent_id?: string | null
          slug: string
          sort_order?: number | null
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          description?: string | null
          id?: string
          image_url?: string | null
          is_active?: boolean | null
          name?: string
          parent_id?: string | null
          slug?: string
          sort_order?: number | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "categories_parent_id_fkey"
            columns: ["parent_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["id"]
          },
        ]
      }
      products: {
        Row: {
          id: string;
          store_id: string;
          name: string;
          slug: string;
          description: string | null;
          price: number;
          compare_price: number | null;
          cost_per_item: number | null;
          margin_percentage: number | null;
          sku: string | null;
          barcode: string | null;
          inventory_quantity: number | null;
          track_inventory: boolean | null;
          continue_selling_when_out_of_stock: boolean | null;
          status: string;
          featured: boolean;
          category_id: string;
          images: string[] | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          store_id: string;
          name: string;
          slug: string;
          description?: string | null;
          price: number;
          compare_price?: number | null;
          cost_per_item?: number | null;
          margin_percentage?: number | null;
          sku?: string | null;
          barcode?: string | null;
          inventory_quantity?: number | null;
          track_inventory?: boolean | null;
          continue_selling_when_out_of_stock?: boolean | null;
          status?: string;
          featured?: boolean;
          category_id: string;
          images?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          store_id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          price?: number;
          compare_price?: number | null;
          cost_per_item?: number | null;
          margin_percentage?: number | null;
          sku?: string | null;
          barcode?: string | null;
          inventory_quantity?: number | null;
          track_inventory?: boolean | null;
          continue_selling_when_out_of_stock?: boolean | null;
          status?: string;
          featured?: boolean;
          category_id?: string;
          images?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "products_store_id_fkey";
            columns: ["store_id"];
            isOneToOne: false;
            referencedRelation: "stores";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "products_category_id_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["id"];
          }
        ];
      };
      stores: {
        Row: {
          id: string;
          owner_id: string;
          name: string;
          slug: string;
          description: string | null;
          logo_url: string | null;
          cover_image_url: string | null;
          address: Json | null;
          contact_info: Json | null;
          business_hours: Json | null;
          status: string;
          featured: boolean | null;
          rating: number | null;
          total_reviews: number | null;
          created_at: string | null;
          updated_at: string | null;
          total_orders: number | null;
          monthly_revenue: number | null;
          commission_rate: number | null;
          phone: string | null;
          email: string | null;
        };
        Insert: {
          id?: string;
          owner_id: string;
          name: string;
          slug: string;
          description?: string | null;
          logo_url?: string | null;
          cover_image_url?: string | null;
          address?: Json | null;
          contact_info?: Json | null;
          business_hours?: Json | null;
          status?: string;
          featured?: boolean | null;
          rating?: number | null;
          total_reviews?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
          total_orders?: number | null;
          monthly_revenue?: number | null;
          commission_rate?: number | null;
          phone?: string | null;
          email?: string | null;
        };
        Update: {
          id?: string;
          owner_id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          logo_url?: string | null;
          cover_image_url?: string | null;
          address?: Json | null;
          contact_info?: Json | null;
          business_hours?: Json | null;
          status?: string;
          featured?: boolean | null;
          rating?: number | null;
          total_reviews?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
          total_orders?: number | null;
          monthly_revenue?: number | null;
          commission_rate?: number | null;
          phone?: string | null;
          email?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "stores_owner_id_fkey";
            columns: ["owner_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
      profiles: {
        Row: {
          id: string;
          first_name: string | null;
          last_name: string | null;
          email: string | null;
          phone: string | null;
          avatar_url: string | null;
          role: string | null;
          status: string | null;
          email_verified: boolean | null;
          email_verified_at: string | null;
          verification_email_sent_at: string | null;
          is_blocked: boolean | null;
          blocked_at: string | null;
          blocked_reason: string | null;
          last_login_at: string | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          first_name?: string | null;
          last_name?: string | null;
          email?: string | null;
          phone?: string | null;
          avatar_url?: string | null;
          role?: string | null;
          status?: string | null;
          email_verified?: boolean | null;
          email_verified_at?: string | null;
          verification_email_sent_at?: string | null;
          is_blocked?: boolean | null;
          blocked_at?: string | null;
          blocked_reason?: string | null;
          last_login_at?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          first_name?: string | null;
          last_name?: string | null;
          email?: string | null;
          phone?: string | null;
          avatar_url?: string | null;
          role?: string | null;
          status?: string | null;
          email_verified?: boolean | null;
          email_verified_at?: string | null;
          verification_email_sent_at?: string | null;
          is_blocked?: boolean | null;
          blocked_at?: string | null;
          blocked_reason?: string | null;
          last_login_at?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      driver_status: {
        Row: {
          id: string;
          driver_id: string;
          is_online: boolean;
          last_location: Json;
          last_updated: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          driver_id: string;
          is_online?: boolean;
          last_location?: Json;
          last_updated?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          driver_id?: string;
          is_online?: boolean;
          last_location?: Json;
          last_updated?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "driver_status_driver_id_fkey";
            columns: ["driver_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
      merchant_applications: {
        Row: {
          id: string;
          user_id?: string;
          business_name: string;
          business_type: string;
          contact_person_first_name: string;
          contact_person_last_name: string;
          email: string;
          phone: string;
          business_address: Json;
          business_description: string | null;
          business_license_number: string | null;
          tax_id: string | null;
          estimated_monthly_revenue: number | null;
          previous_experience: string | null;
          status: string;
          admin_notes: string | null;
          reviewed_at: string | null;
          reviewed_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          business_name: string;
          business_type: string;
          contact_person_first_name: string;
          contact_person_last_name: string;
          email: string;
          phone: string;
          business_address: Json;
          business_description?: string | null;
          business_license_number?: string | null;
          tax_id?: string | null;
          estimated_monthly_revenue?: number | null;
          previous_experience?: string | null;
          status?: string;
          admin_notes?: string | null;
          reviewed_at?: string | null;
          reviewed_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          business_name?: string;
          business_type?: string;
          contact_person_first_name?: string;
          contact_person_last_name?: string;
          email?: string;
          phone?: string;
          business_address?: Json;
          business_description?: string | null;
          business_license_number?: string | null;
          tax_id?: string | null;
          estimated_monthly_revenue?: number | null;
          previous_experience?: string | null;
          status?: string;
          admin_notes?: string | null;
          reviewed_at?: string | null;
          reviewed_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      driver_applications: {
        Row: {
          id: string;
          user_id?: string;
          first_name: string;
          last_name: string;
          email: string;
          phone: string;
          address: Json;
          vehicle_info: Json;
          documents: Json;
          status: string;
          admin_notes: string | null;
          reviewed_at: string | null;
          reviewed_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          first_name: string;
          last_name: string;
          email: string;
          phone: string;
          address: Json;
          vehicle_info: Json;
          documents: Json;
          status?: string;
          admin_notes?: string | null;
          reviewed_at?: string | null;
          reviewed_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          first_name?: string;
          last_name?: string;
          email?: string;
          phone?: string;
          address?: Json;
          vehicle_info?: Json;
          documents?: Json;
          status?: string;
          admin_notes?: string | null;
          reviewed_at?: string | null;
          reviewed_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      notifications: {
        Row: {
          id: string;
          user_id: string | null;
          type: string;
          title: string;
          message: string;
          read: boolean | null;
          related_id: string | null;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          type: string;
          title: string;
          message: string;
          read?: boolean | null;
          related_id?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          type?: string;
          title?: string;
          message?: string;
          read?: boolean | null;
          related_id?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never
    };
    Functions: {
      [_ in never]: never
    };
    Enums: {
      [_ in never]: never
    };
    CompositeTypes: {
      [_ in never]: never
    };
  };
};

export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row'];
export type TablesInsert<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert'];
export type TablesUpdate<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update'];
